/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_windystory_hellojni_JNI */

#ifndef _Included_com_windystory_hellojni_JNI
#define _Included_com_windystory_hellojni_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_windystory_hellojni_JNI
 * Method:    Hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_windystory_hellojni_JNI_Hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
